apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: nvanbenschoten-com-tls
spec:
  secretName: nvanbenschoten-com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: nvanbenschoten.com
  dnsNames:
    - nvanbenschoten.com
    - www.nvanbenschoten.com
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - nvanbenschoten.com
          - www.nvanbenschoten.com
