apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      component: api
  template:
    metadata:
      labels:
        component: api
    spec:
      containers:
        - name: server
          image: nvanbenschoten/multi-server
          ports:
            - containerPort: 5000
          env:
            - name: REDIS_HOST
              value: redis-cluster-ip-service
            - name: REDIS_PORT
              value: "6379"
            - name: PGHOST
              value: cockroach-cluster-ip-service
            - name: PGPORT
              value: "26257"
            - name: PGDATABASE
              value: postgres
            - name: PGUSER
              value: root
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: cockroach-password
                  key: PGPASSWORD
